### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by nofootnotes** [liberty-x/lxsearch#33]
A bit of folder structuring wouldn't go amiss! Makes it easier to see what each file is doing.

**Comment by RachBLondon** [comment]
Good point, would you suggest having difficulty folders for front end, backend and api?

**Comment by claireinez** [comment]
The best way to learn good folder structure is to have a look through other repos on GitHub, and see how others have done it. There are quite a few good ones under the Founders & Coders organisation so have look there!
